/////////QUESTION23///////////
var car = 'subaru';
console.log("is car =='subaru'? Ipredict true");
console.log(car == 'subaru');
console.log("is car !=='subaru'? Ipredict true");
console.log(car !== 'subaru');
console.log("is car =='civic'? Ipredict false");
console.log(car == "civic");
console.log("is car !=='civic'? Ipredict true");
console.log(car !== "civic");
console.log("is car =='mira'? Ipredict false");
console.log(car == "mira");
console.log("is car !=='mira'? Ipredict true");
console.log(car !== "mira");
console.log("is car =='corola'? Ipredict false");
console.log(car == "corola");
console.log("is car !=='corola'? Ipredict true");
console.log(car !== "corola");
console.log("is car =='suzuki'? Ipredict false");
console.log(car == "suzuki");
console.log("is car !=='suzuki'? Ipredict true");
console.log(car !== "suzuki");
